services:
  db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: inclass
      MARIADB_USER: inclass
      MARIADB_PASSWORD: inclass
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - mariadb_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10




  app:
    platform: linux/amd64
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DISPLAY: host.docker.internal:0.0
    command:
      [
        "java",
        "-Ddb.url=jdbc:mariadb://db:3306/inclass",
        "-Ddb.user=inclass",
        "-Ddb.password=inclass",
        "--module-path",
        "/javafx-sdk/lib",
        "--add-modules",
        "javafx.controls,javafx.fxml",
        "-jar",
        "app.jar"
      ]

volumes:
  mariadb_data: